blog_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from config import settings

app_name = 'blog'
urlpatterns = [
    path('', views.BlogList.as_view(), name='blogList_page'),
    path('detail/<slug:slug>', views.BlogDetail.as_view(), name='blogDetail_page'),
    path('tag/<slug:tag>', views.blog_tag, name='blogTagList_page'),
    path('category/<slug:category>', views.blog_category, name='blogCategoryList_page'),
    path('search', views.blog_search, name='blogSearch_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('food/', include('food_app.urls')),
    path('reserve/', include('reservation_app.urls')),
    path('blog/', include('blog_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

class Blog(models.Model):
    title = models.CharField(max_length=30, verbose_name='title', unique=True)
    body = models.TextField(verbose_name='text')
    image = models.ImageField(verbose_name='blog image', upload_to='Blog',
                              help_text='The size of the images should be 470x570 pixels')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='grouping', related_name='blog')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='writer')
    tag = models.ManyToManyField('Tag', verbose_name='tags', related_name='tag')
    situation = models.BooleanField(verbose_name='publication status', default=False)
    created_at = models.DateField(verbose_name='creation date', auto_now_add=True)
    update = models.DateTimeField(verbose_name='Update history', auto_now=True)
    slug = models.SlugField(blank=True, verbose_name='aslag',
                            help_text='this field is filled automatically')

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Blog, self).save()

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

class Category(models.Model):
    title = models.CharField(max_length=25, verbose_name='Category title', unique=True)
    slug = models.SlugField(blank=True, verbose_name='Aslag',
                            help_text='This field is filled automatically')
    date = models.DateTimeField(verbose_name='creation date', auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Category, self).save()
    class Meta:
        verbose_name = 'Grouping'
        verbose_name_plural = 'categories'



class Tag(models.Model):
    title = models.CharField(max_length=25, verbose_name='Title tag', unique=True)
    slug = models.SlugField(blank=True, unique=True, verbose_name='Aslag',
                            help_text='This field is filled automatically')
    date = models.DateTimeField(verbose_name='creation date', auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Tag, self).save()

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'Tags'


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments', verbose_name='Article',
                             help_text='What article is the intended comment for?')
    name = models.CharField(max_length=20, verbose_name='first name and last name')
    email = models.EmailField(verbose_name='email', null=True)
    text = models.TextField(verbose_name='Comment text')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies',
                               verbose_name='Reply to the comment',
                               help_text='If this comment is in response to another comment, it will be completed',
                               null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='creation date')

    def __str__(self):
        return self.text[:10]

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'Comments'

blog_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Blog, Category, Tag, Comment


class BlogList(View):
    def get(self, request):
        blogs = Blog.objects.all()
        return render(request, 'blog_app/blog.html', {'blogs': blogs})


class BlogDetail(View):
    def get(self, request, slug):
        blog = get_object_or_404(Blog, slug=slug)
        categorys = Category.objects.all()
        tags = Tag.objects.all().filter(tag=blog)
        recent_blog = Blog.objects.all().order_by('-created_at')[:5]

        return render(request, 'blog_app/blog-details.html',
                      {'blog': blog, 'categorys': categorys, 'tags': tags, 'recent_blog': recent_blog})

    def post(self, request, slug):
        blog = get_object_or_404(Blog, slug=slug)
        categorys = Category.objects.all()
        tags = Tag.objects.all().filter(tag=blog)
        recent_blog = Blog.objects.all().order_by('-created_at')[:5]

        name = request.POST.get('name')
        email = request.POST.get('email')
        text = request.POST.get('text')
        parent_id = request.POST.get('parent_id')

        Comment.objects.create(blog=blog, name=name, email=email, text=text, parent_id=parent_id)

        return render(request, 'blog_app/blog-details.html',
                      {'blog': blog, 'categorys': categorys, 'tags': tags, 'recent_blog': recent_blog})


def blog_tag(request, tag):
    blogs = Blog.objects.filter(tag__slug=tag)
    return render(request, 'blog_app/blog.html', {'blogs': blogs})


def blog_category(request, category):
    blogs = Blog.objects.filter(category__slug=category)
    return render(request, 'blog_app/blog.html', {'blogs': blogs})


def blog_search(request):
    if request.method == 'POST':
        query = request.POST.get('search')
        blogs = Blog.objects.filter(title__icontains=query)
        return render(request, 'blog_app/blog.html', {'blogs': blogs})

blog_app/templates/blog_app/blog-details.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Blog</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog details -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                        <h2>Blog</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-12">
                    <div class="blog-inner-details-page">
                        <div class="blog-inner-box">
                            <div class="side-blog-img" style="width: fit-content">
                                <img class="img-fluid" src="{{ blog.image.url }}" alt="blog image">
                                <div class="date-blog-up">
                                    {{ blog.category }}
                                </div>
                            </div>
                            <div class="inner-blog-detail details-page">
                                <h3>{{ blog.title }}</h3>
                                <ul>
                                    <li><i class="zmdi zmdi-account"></i>Posted By :
                                        <span>{{ blog.author.first_name }} {{ blog.author.last_name }}</span>
                                    </li>
                                    <li>|</li>
                                    <li><i class="zmdi zmdi-time"></i>Time :
                                        <span>{{ blog.created_at|date:'Y m d' }}</span>
                                    </li>
                                </ul>
                                <p>{{ blog.body }}</p>
                            </div>
                        </div>
                        <div class="blog-comment-box">
                            <h3>Comments</h3>
                            {% for comment in blog.comments.all %}
                                {% if comment.parent == null %}
                                    <div class="comment-item">
                                        <div>
                                            <div class="pull-left">
                                                <span>{{ comment.name.capitalize }}</span>
                                            </div>
                                            <div class="pull-right">
                                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                                                Date :<span>{{ comment.created_at|date:'Y m d' }}</span>
                                            </div>
                                            <div class="des-l">
                                                <p>{{ comment.text }}</p>
                                            </div>
                                            <button class="btn btn-common" onclick="setParentId({{ comment.id }})">
                                                <i class="fa fa-reply" aria-hidden="true"></i>
                                                Reply
                                            </button>
                                        </div>
                                    </div>
                                    {% for reply in comment.replies.all %}
                                        <div class="comment-item children">
                                            <div>
                                                <div class="pull-left">
                                                    <span>{{ reply.name.capitalize }}</span>
                                                </div>
                                                <div class="pull-right">
                                                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                                                    Date :<span>{{ comment.created_at|date:'Y m d' }}</span>
                                                </div>
                                                <div class="des-l">
                                                    <p>{{ reply.text }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="comment-respond-box">
                            <h3>Leave your comment</h3>
                            <div class="comment-respond-form">
                                <form id="commentrespondform" class="comment-form-respond row" method="post">
                                    {% csrf_token %}
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <input id="name_com" class="form-control" name="name" placeholder="Name"
                                                   type="text">
                                        </div>
                                        <div class="form-group">
                                            <input id="email_com" class="form-control" name="email"
                                                   placeholder="Your Email" type="email">
                                        </div>
                                        <div class="form-group">
                                            <input id="parent_id" name="parent_id" type="number" value="" hidden>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <textarea class="form-control" id="textarea_com" placeholder="Your Message"
                                                      rows="2" name="text"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <button class="btn btn-submit" type="submit">Submit comment</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
                    <div class="right-side-blog">
                        <h3>Search</h3>
                        <form method="post" action="{% url 'blog:blogSearch_page' %}">
                            {% csrf_token %}
                            <div class="blog-search-form">
                                <input name="search" placeholder="Search blog" type="text">
                                <button class="search-btn">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
                        <h3>Categories</h3>
                        <div class="blog-categories">
                            {% for category in categorys %}
                                <ul>
                                    <li>
                                        <a href="{% url 'blog:blogCategoryList_page' category.slug %}"><span>{{ category.title }}</span></a>
                                    </li>
                                </ul>
                            {% endfor %}
                        </div>
                        <h3>Recent Post</h3>
                        <div class="post-box-blog">
                            <div class="recent-post-box">
                                {% for blog in recent_blog %}
                                    {% if blog.situation %}
                                        <div class="recent-box-blog">
                                            <a href="{% url 'blog:blogDetail_page' blog.slug %}">
                                                <div class="recent-img">
                                                    <img class="img-fluid" src="{{ blog.image.url }}" alt="blog image"
                                                         style="width: 80px;height: 80px">
                                                </div>
                                                <div class="recent-info">
                                                    <ul>
                                                        <li>
                                                            <i class="zmdi zmdi-account"></i>
                                                            Posted By :
                                                            <span>{{ blog.author.first_name }} {{ blog.author.last_name }}</span>
                                                        </li>
                                                        <li>|</li>
                                                        <li><i class="zmdi zmdi-time"></i>Date :
                                                            <span>{{ blog.created_at|date:'Y m d' }}</span></li>
                                                    </ul>
                                                    <h4>{{ blog.title }}</h4>
                                                </div>
                                            </a>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <h3>Recent Tag</h3>
                        <div class="blog-tag-box">
                            <ul class="list-inline tag-list">
                                {% for tag in tags %}
                                    <li class="list-inline-item">
                                        <a href="{% url 'blog:blogTagList_page' tag.slug %}">{{ tag.title.capitalize }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- End details -->
    <script>
        const setParentId = id => {
            let inputElem = document.getElementById('parent_id');
            inputElem.value = id;
            let inputsTitle = document.querySelector('.comment-respond-box h3');
            inputsTitle.textContent = 'Leave your reply';
            window.location.href = '#name_com';
        }
    </script>
{% endblock %}

blog_app/templates/blog_app/blog.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Blog</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                        <h2>Blog</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for blog in blogs %}
                    {% if blog.situation %}
                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="blog-box-inner">
                                <div class="blog-img-box">
                                    <img class="img-fluid" src="{{ blog.image.url }}" alt="blog image">
                                </div>
                                <div class="blog-detail">
                                    <h4>{{ blog.title }}</h4>
                                    <ul>
                                        <li><span>Post by {{ blog.author.first_name }} {{ blog.author.last_name }}</span></li>
                                        <li>|</li>
                                        <li><span>{{ blog.created_at|date:'Y m d' }}</span></li>
                                    </ul>
                                    <p>{{ blog.body|truncatewords:50 }}</p>
                                    <a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:blogDetail_page' blog.slug %}">Read More</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- End blog -->
{% endblock %}