blog_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from config import settings

app_name = 'blog'
urlpatterns = [
    path('', views.BlogList.as_view(), name='blogList_page'),
    path('detail/<slug:slug>', views.BlogDetail.as_view(), name='blogDetail_page'),
    path('tag/<slug:tag>', views.blog_tag, name='blogTagList_page'),
    path('category/<slug:category>', views.blog_category, name='blogCategoryList_page'),
    path('search', views.blog_search, name='blogSearch_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('food/', include('food_app.urls')),
    path('reserve/', include('reservation_app.urls')),
    path('blog/', include('blog_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from config import settings

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(), name='home_page'),
    path('menu', views.Menu.as_view(), name='menu_page'),
    path('about', views.About.as_view(), name='about_page'),
    path('contact', views.Contact.as_view(), name='contact_page'),
    path('gallery', views.GalleryView.as_view(), name='gallery_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation_app/urls.py
from django.urls import path
from .views import Reserve

app_name = 'reservation'
urlpatterns = [
    path('', Reserve.as_view(), name='reserve_page')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

{% include 'includes/header.html' %}

<body>
<!-- Start header -->
<header class="top-navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/#">
                <img src="{% static 'images/text-logo.svg' %}" alt=""/>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food"
                    aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbars-rs-food">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if request.resolver_match.url_name == 'home_page' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'main:home_page' %}">Home</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'menu_page' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'main:menu_page' %}">Menu</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'about_page' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'main:about_page' %}">About</a>
                    </li>
                    <li class="nav-item dropdown {% if request.resolver_match.url_name == 'reserve_page' or request.resolver_match.url_name == 'gallery_page' %}active{% endif %}">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-a">
                            <a class="dropdown-item" href="{% url 'reservation:reserve_page' %}">Reservation</a>
                            <a class="dropdown-item" href="{% url 'main:gallery_page' %}">Gallery</a>
                        </div>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'blogList_page' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'blog:blogList_page' %}">Blogs</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'contact_page' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'main:contact_page' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End header -->

{% block main %}

{% endblock %}

<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +998901234567
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        yourmail@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        800, Lorem Street, US
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->
<!-- Start Footer -->
<footer class="footer-area bg-f">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <h3>About Us</h3>
                <p>Integer cursus scelerisque ipsum id efficitur. Donec a dui fringilla, gravida lorem ac, semper magna.
                    Aenean rhoncus ac lectus a interdum. Vivamus semper posuere dui, at ornare turpis ultrices sit amet.
                    Nulla cursus lorem ut nisi porta, ac eleifend arcu ultrices.</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Opening hours</h3>
                <p><span class="text-color">Monday: </span>Closed</p>
                <p><span class="text-color">Tue-Wed :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Thu-Fri :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Sat-Sun :</span> 5:PM - 10PM</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Contact information</h3>
                <p class="lead">Ipsum Street, Lorem Tower, Tashkent, 508000</p>
                <p class="lead"><a href="#">+998901234567</a></p>
                <p><a href="#"> info@admin.com</a></p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Subscribe</h3>
                <div class="subscribe_form">
                    <form class="subscribe_form">
                        <input name="EMAIL" id="subs-email" class="form_input" placeholder="Email Address..."
                               type="email">
                        <button type="submit" class="submit">SUBSCRIBE</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
                <ul class="list-inline f-social">
                    <li class="list-inline-item"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                    </li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- End Footer -->

<a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

{% include 'includes/footer_tags.html' %}
</body>
</html>