config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('food/', include('food_app.urls')),
    path('reserve/', include('reservation_app.urls')),
    path('blog/', include('blog_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_app/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('detail/<slug:slug>', views.FoodDetail.as_view(), name='FoodDetail_page'),
    path('search', views.food_search, name='foodSearch_page'),
]

main_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from config import settings

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(), name='home_page'),
    path('menu', views.Menu.as_view(), name='menu_page'),
    path('about', views.About.as_view(), name='about_page'),
    path('contact', views.Contact.as_view(), name='contact_page'),
    path('gallery', views.GalleryView.as_view(), name='gallery_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_app/models.py
from django.db import models
from django.utils.text import slugify


class Food(models.Model):
    TYPES = [
        ('drinks', 'Beverages'),
        ('lunch', 'Lunch'),
        ('dinner', 'the evening'),
    ]

    food_type = models.CharField(max_length=20, choices=TYPES, verbose_name='type of food')

    name = models.CharField(max_length=20, verbose_name='food name')

    price = models.PositiveIntegerField(verbose_name='The price of food')

    descripion = models.TextField(verbose_name='Description of food')

    image = models.ImageField(upload_to='Foods', verbose_name='photo of food',
                              help_text='Images should be in 800x480 size')

    slug = models.SlugField(blank=True, unique=True, verbose_name='Aslag',
                            help_text='This field is filled automatically')

    update_at = models.DateTimeField(verbose_name='Update date', auto_now=True)
    date = models.DateTimeField(verbose_name='creation date', auto_now_add=True)

    situation = models.BooleanField(default=True, verbose_name='Availability of food')
    status = models.BooleanField(default=False, verbose_name='Condition', help_text='Publication status on the site')

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        super(Food, self).save()

    class Meta:
        verbose_name = 'Food'
        verbose_name_plural = 'foods'


class Comment(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE, related_name='comments', verbose_name='Food',
                             help_text='Which food is the comment intended for?')

    name = models.CharField(max_length=20, verbose_name='first name and last name')

    email = models.EmailField(verbose_name='email', null=True)

    text = models.TextField(verbose_name='Comment text')

    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', verbose_name='Reply to the comment',
                               help_text='If this comment is in response to another comment, it will be completed', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='creation date')

    def __str__(self):
        return self.text[:10]

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'Comments'

food_app/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Food, Comment


class FoodDetail(View):
    def get(self, request, slug):
        food = get_object_or_404(Food, slug=slug)
        recent_foods = Food.objects.all().order_by('-date')[:5]
        food_types = Food.TYPES

        return render(request, 'food_app/food-details.html',
                      {'food_details': food, 'recent_foods': recent_foods, 'food_types': food_types})

    def post(self, request, slug):
        food = get_object_or_404(Food, slug=slug)
        recent_foods = Food.objects.all().order_by('-date')[:5]
        food_types = Food.TYPES

        name = request.POST.get('name')
        email = request.POST.get('email')
        text = request.POST.get('text')
        parent_id = request.POST.get('parent_id')
        print(parent_id, type(parent_id))
        print(name, email)
        print(text)

        Comment.objects.create(food=food, name=name, email=email, text=text, parent_id=parent_id)

        return render(request, 'food_app/food-details.html',
                      {'food_details': food, 'recent_foods': recent_foods, 'food_types': food_types})



def food_search(request):
    if request.method == 'POST':
        query = request.POST.get('search')
        print(query)
        food = get_object_or_404(Food, name__icontains=query)
        recent_foods = Food.objects.all().order_by('-date')[:5]
        food_types = Food.TYPES
        return render(request, 'food_app/food-details.html',
                      {'food_details': food, 'recent_foods': recent_foods, 'food_types': food_types})

food_app/templates/food_app/food-details.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>{{ food_details.name.capitalize }} Detail</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog details -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                        <h2>Detail</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-12">
                    <div class="blog-inner-details-page">
                        <div class="blog-inner-box">
                            <div class="side-blog-img">
                                <img class="img-fluid" src="{{ food_details.image.url }}" alt="food image">
                                <div class="date-blog-up">{{ food_details.food_type.capitalize }}</div>
                            </div>
                            <div class="inner-blog-detail details-page">
                                <h3>{{ food_details.descripion }}</h3>
                                <ul>
                                    <li><i class="zmdi zmdi-account"></i>Price : <span>${{ food_details.price }}</span>
                                    </li>
                                    <li>|</li>
                                    {% if food_details.situation == True %}
                                        <li><i class="zmdi zmdi-time"></i>Food Status : <span>Ready</span></li>
                                    {% else %}
                                        <li><i class="zmdi zmdi-time"></i>Food Status : <span>Not Ready</span></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                        <div class="blog-comment-box">
                            <h3>Comments</h3>
                            {% for comment in food_details.comments.all %}
                                {% if comment.parent == null %}
                                    <div class="comment-item">
                                        <div>
                                            <div class="pull-left">
                                                <span>{{ comment.name.capitalize }}</span>
                                            </div>
                                            <div class="pull-right">
                                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                                                Date :<span>{{ comment.created_at|date:'Y m d' }}</span>
                                            </div>
                                            <div class="des-l">
                                                <p>{{ comment.text }}</p>
                                            </div>
                                            <button class="btn btn-common" onclick="setParentId({{ comment.id }})">
                                                <i class="fa fa-reply" aria-hidden="true"></i>
                                                Reply
                                            </button>
                                        </div>
                                    </div>
                                    {% for reply in comment.replies.all %}
                                        <div class="comment-item children">
                                            <div>
                                                <div class="pull-left">
                                                    <span>{{ reply.name.capitalize }}</span>
                                                </div>
                                                <div class="pull-right">
                                                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                                                    Date :<span>{{ comment.created_at|date:'Y m d' }}</span>
                                                </div>
                                                <div class="des-l">
                                                    <p>{{ reply.text }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="comment-respond-box">
                            <h3>Leave your comment </h3>
                            <div class="comment-respond-form">
                                <form id="commentrespondform" class="comment-form-respond row" method="post">
                                    {% csrf_token %}
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <input id="name_com" class="form-control" name="name" placeholder="Name"
                                                   type="text">
                                        </div>
                                        <div class="form-group">
                                            <input id="email_com" class="form-control" name="email"
                                                   placeholder="Your Email" type="email">
                                        </div>
                                        <div class="form-group">
                                            <input id="parent_id" name="parent_id" type="number" value="" hidden>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <textarea class="form-control" id="textarea_com" placeholder="Your Message"
                                                      rows="2" name="text">
                                            </textarea>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <button class="btn btn-submit" type="submit">Submit comment</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
                    <div class="right-side-blog">
                        <h3>Search</h3>
                        <form method="post" action="{% url 'food:foodSearch_page' %}">
                            {% csrf_token %}
                            <div class="blog-search-form">
                                <input name="search" placeholder="Search blog" type="text">
                                <button class="search-btn">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
                        <h3>Foods Types</h3>
                        <div class="blog-categories">
                            <ul>
                                {% for type in food_types %}
                                    <li><a href="{% url 'main:menu_page' %}"><span>{{ type.0 }}</span></a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <h3>Other Foods</h3>
                        <div class="post-box-blog">
                            <div class="recent-post-box">
                                {% for food in recent_foods %}
                                    {% if food.status %}
                                        <div class="recent-box-blog">
                                            <a href="{% url 'food:FoodDetail_page' food.slug %}">
                                                <div class="recent-img">
                                                    <img class="img-fluid" src="{{ food.image.url }}" alt="food image"
                                                         style="width: 90px;height: 65px">
                                                </div>
                                                <div class="recent-info">
                                                    <ul>
                                                        <li><i class="zmdi zmdi-account"></i>
                                                            <span>{{ food.name }}</span>
                                                        </li>
                                                        <li>|</li>
                                                        <li><i class="zmdi zmdi-time"></i>
                                                            <span>{{ food.food_type }}</span>
                                                        </li>
                                                    </ul>
                                                    <h4>{{ food.descripion|truncatechars:40 }}</h4>
                                                </div>
                                            </a>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- End details -->
    <script>
        const setParentId = id => {
            let inputElem = document.getElementById('parent_id');
            inputElem.value = id;
            let inputsTitle = document.querySelector('.comment-respond-box h3');
            inputsTitle.textContent = 'Leave your reply';
            window.location.href = '#name_com';
        }
    </script>
{% endblock %}